#pragma once

#define FIRE_LAND_DECL_VK_FUNCTION(NAME) PFN_##NAME NAME;

#define FIRE_LAND_RESOLVE_VK_FUNCTION(RESOLVER, OBJECT, NAME) \
	NAME = reinterpret_cast<PFN_##NAME>(RESOLVER(OBJECT, #NAME));

#define FIRE_LAND_RESOLVE_VK_FUNCTION_COND(RESOLVER, OBJECT, NAME, RET_ERR) \
	FIRE_LAND_RESOLVE_VK_FUNCTION(RESOLVER, OBJECT, NAME) \
	if(!NAME) \
		return RET_ERR;

#define FIRE_LAND_RESOLVE_VK_FUNCTION_COUNT(RESOLVER, OBJECT, NAME, COUNTER) \
	NAME = reinterpret_cast<PFN_##NAME>(RESOLVER(OBJECT, #NAME)); \
	if(NAME) \
		COUNTER++;

#define FIRE_LAND_RESOLVE_GLOBAL_RESOLVER_COND(GLOBAL_RESOLVER, GLOBAL_RESOLVER_NAME, RET_ERR) \
	GLOBAL_RESOLVER_NAME = GLOBAL_RESOLVER; \
	if(!GLOBAL_RESOLVER_NAME) \
		return RET_ERR;

#define FIRE_LAND_RESOLVE_INSTANCE_RESOLVER_COND(GLOBAL_RESOLVER, INSTANCE, INSTANCE_RESOLVER_NAME, RET_ERR) \
	FIRE_LAND_RESOLVE_VK_FUNCTION_COND(GLOBAL_RESOLVER, INSTANCE, INSTANCE_RESOLVER_NAME, RET_ERR) \
	FIRE_LAND_RESOLVE_VK_FUNCTION_COND(INSTANCE_RESOLVER_NAME, INSTANCE, INSTANCE_RESOLVER_NAME, RET_ERR)

#define FIRE_LAND_RESOLVE_DEVICE_RESOLVER_COND(INSTANCE_RESOLVER, INSTANCE, DEVICE_RESOLVER_NAME, DEVICE, RET_ERR) \
	FIRE_LAND_RESOLVE_VK_FUNCTION_COND(INSTANCE_RESOLVER, INSTANCE, DEVICE_RESOLVER_NAME, RET_ERR) \
	FIRE_LAND_RESOLVE_VK_FUNCTION_COND(DEVICE_RESOLVER_NAME, DEVICE, DEVICE_RESOLVER_NAME, RET_ERR)
