//#pragma once

#define STRINGIFY(x) #x

#define FIRE_LAND_DECL_VK_FUNCTION(NAME) PFN_vk##NAME NAME = nullptr;

#define FIRE_LAND_RESOLVE_VK_FUNCTION(RESOLVER, OBJECT, NAME) \
NAME = reinterpret_cast<PFN_vk##NAME>(RESOLVER(OBJECT, STRINGIFY(vk##NAME)));

#define FIRE_LAND_RESOLVE_VK_FUNCTION_COND(RESOLVER, OBJECT, NAME, RET_ERR) \
	FIRE_LAND_RESOLVE_VK_FUNCTION(RESOLVER, OBJECT, NAME) \
	if(!NAME) \
		return RET_ERR;

#define FIRE_LAND_RESOLVE_VK_FUNCTION_COUNT(RESOLVER, OBJECT, NAME, COUNTER) \
	FIRE_LAND_RESOLVE_VK_FUNCTION(RESOLVER, OBJECT, NAME) \
	if(NAME) \
		COUNTER++;
