#undef HRS_ALLOW_REFL_PRIVATE_ACCESS

#undef HRS_REFL_BEGIN

#undef HRS_REFL_END

#undef HRS_REFL_MEMBER_FIELDS_BEGIN

#undef HRS_REFL_MEMBER_FIELDS_END

#undef HRS_REFL_MEMBER_FIELD

#undef HRS_REFL_USINGS_BEGIN

#undef HRS_REFL_USINGS_END

#undef HRS_REFL_USING_FIELD

#undef HRS_REFL_STATIC_FIELDS_BEGIN

#undef HRS_REFL_STATIC_FIELDS_END

#undef HRS_REFL_PARENT_CLASSES

#undef HRS_REFL_STATIC_FIELD