#undef HRS_REFL_ENUM

#undef HRS_REFL_ENUM_BEGIN

#undef HRS_REFL_ENUM_TYPED_BEGIN

#undef HRS_REFL_ENUM_NS_BEGIN

#undef HRS_REFL_ENUM_NS_TYPED_BEGIN

#undef HRS_REFL_ENUM_ATTRIBUTES

#undef HRS_REFL_ENUM_END
