#undef HRS_REFL_ENUM_BEGIN_EXISTED

#undef HRS_REFL_ENUM_BEGIN

#undef HRS_REFL_ENUM_TYPED_BEGIN

#undef HRS_REFL_ENUM_NS_BEGIN

#undef HRS_REFL_ENUM_NS_TYPED_BEGIN

#undef HRS_REFL_ENUM_BODY

#undef HRS_REFL_ENUM_END
