#define LOADER_GEN_LIST() \
	FIRE_LAND_LOADER_BEGIN_MIXED(AllocatorLoader, Init) \
		FIRE_LAND_MIXED_LOADER_USE_DEVICE_SOURCE() \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkAllocateMemory) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkFreeMemory) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkUnmapMemory) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkMapMemory) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkCreateBuffer) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkBindBufferMemory) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkGetBufferMemoryRequirements) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkDestroyBuffer) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkCreateImage) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkBindImageMemory) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkGetImageMemoryRequirements) \
			FIRE_LAND_LOADER_REQUIRED_FUNCTION(vkDestroyImage) \
		FIRE_LAND_MIXED_LOADER_UNUSE_SOURCE() \
	FIRE_LAND_LOADER_END()
